In [2]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

data_folder = project_root / "data"
data_folder.mkdir(exist_ok=True)

data = {
    "trial_id": [1, 2],
    "date": ["2026-06-21", "2026-06-21"],
    "condition": ["calm", "stress"],
    "resting_hr": [75, 75],
    "post_exercise_hr": [141, 144],
    "hr_60s": [83, 86],
    "completion_time": ["N/A", "2:17.46"],
    "side_notes": [
        "Approx 2h after hitting with Richard, 8 hours of sleep, 0 mistakes made while skipping",
        "Approx 2h after hitting with Richard, 8 hours of sleep, 7 mistakes made while skipping"
    ]
}

df = pd.DataFrame(data)

df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

df = df[
    [
        "trial_id",
        "date",
        "condition",
        "resting_hr",
        "post_exercise_hr",
        "hr_60s",
        "hrr",
        "completion_time",
        "side_notes"
    ]
]

df.to_csv(data_folder / "research_data.csv", index=False)

df

,trial_id,date,condition,resting_hr,post_exercise_hr,hr_60s,hrr,completion_time,side_notes
0,1,2026-06-21,calm,75,141,83,58,N/A,"Approx 2h after hitting with Richard, 8 hours ..."
1,2,2026-06-21,stress,75,144,86,58,2:17.46,"Approx 2h after hitting with Richard, 8 hours ..."

In [3]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path)

df

,trial_id,date,condition,resting_hr,post_exercise_hr,hr_60s,hrr,completion_time,side_notes
0,1,2026-06-21,calm,75,141,83,58,NaN,"Approx 2h after hitting with Richard, 8 hours ..."
1,2,2026-06-21,stress,75,144,86,58,2:17.46,"Approx 2h after hitting with Richard, 8 hours ..."

In [4]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path, keep_default_na=False)

# Add the two new scale columns if they do not already exist
if "exertion_scale" not in df.columns:
    df["exertion_scale"] = ""

if "stress_scale" not in df.columns:
    df["stress_scale"] = ""

# Add scale values for trials 1-4
scale_values = {
    1: {"exertion_scale": 6, "stress_scale": 3},
    2: {"exertion_scale": 6, "stress_scale": 6},
    3: {"exertion_scale": 5, "stress_scale": 3},
    4: {"exertion_scale": 6, "stress_scale": 6},
}

for trial_id, values in scale_values.items():
    for column, value in values.items():
        df.loc[df["trial_id"] == trial_id, column] = value

# New trial rows
new_rows = pd.DataFrame([
    {
        "trial_id": 3,
        "date": "2026-06-24",
        "condition": "calm",
        "resting_hr": 75,
        "post_exercise_hr": 143,
        "hr_60s": 88,
        "hrr": 55,
        "completion_time": "N/A",
        "side_notes": "8 hours of sleep; timer shut off at 50 seconds remaining, had to guess; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 3 mistakes were made while skipping",
        "exertion_scale": 5,
        "stress_scale": 3
    },
    {
        "trial_id": 4,
        "date": "2026-06-24",
        "condition": "stress",
        "resting_hr": 75,
        "post_exercise_hr": 153,
        "hr_60s": 91,
        "hrr": 62,
        "completion_time": "2:03.30",
        "side_notes": "8 hours of sleep; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 4 mistakes were made while skipping; made a mistake when doing serial sevens test - did not end at 4, ended on 6",
        "exertion_scale": 6,
        "stress_scale": 6
    }
])

# Only add trials 3 and 4 if they are not already in the table
new_rows = new_rows[~new_rows["trial_id"].isin(df["trial_id"])]

df = pd.concat([df, new_rows], ignore_index=True)

# Recalculate HRR just to make sure it is correct
df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

df.to_csv(data_path, index=False)

df

TypeError: Invalid value '6' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [5]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path, keep_default_na=False)

# Add the two new columns
if "exertion_scale" not in df.columns:
    df["exertion_scale"] = ""

if "stress_scale" not in df.columns:
    df["stress_scale"] = ""

# Add scale values for the existing trials
df.loc[df["trial_id"] == 1, "exertion_scale"] = 6
df.loc[df["trial_id"] == 1, "stress_scale"] = 3

df.loc[df["trial_id"] == 2, "exertion_scale"] = 6
df.loc[df["trial_id"] == 2, "stress_scale"] = 6

# Remove trial 3 and 4 if they already exist, so we do not accidentally duplicate them
df = df[~df["trial_id"].isin([3, 4])]

# Add trial 3 and trial 4
new_rows = pd.DataFrame([
    {
        "trial_id": 3,
        "date": "2026-06-24",
        "condition": "calm",
        "resting_hr": 75,
        "post_exercise_hr": 143,
        "hr_60s": 88,
        "hrr": 55,
        "completion_time": "N/A",
        "side_notes": "8 hours of sleep; timer shut off at 50 seconds remaining, had to guess; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 3 mistakes were made while skipping",
        "exertion_scale": 5,
        "stress_scale": 3
    },
    {
        "trial_id": 4,
        "date": "2026-06-24",
        "condition": "stress",
        "resting_hr": 75,
        "post_exercise_hr": 153,
        "hr_60s": 91,
        "hrr": 62,
        "completion_time": "2:03.30",
        "side_notes": "8 hours of sleep; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 4 mistakes were made while skipping; made a mistake when doing serial sevens test - did not end at 4, ended on 6",
        "exertion_scale": 6,
        "stress_scale": 6
    }
])

df = pd.concat([df, new_rows], ignore_index=True)

# Recalculate heart-rate recovery
df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

# Save the updated table
df.to_csv(data_path, index=False)

df

TypeError: Invalid value '6' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [6]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path, keep_default_na=False)

# Add the two new columns if they do not already exist
if "exertion_scale" not in df.columns:
    df["exertion_scale"] = pd.NA

if "stress_scale" not in df.columns:
    df["stress_scale"] = pd.NA

# Make sure these columns can hold numbers
df["exertion_scale"] = pd.to_numeric(df["exertion_scale"], errors="coerce").astype("Int64")
df["stress_scale"] = pd.to_numeric(df["stress_scale"], errors="coerce").astype("Int64")

# Add scale values for existing trials 1 and 2
df.loc[df["trial_id"] == 1, "exertion_scale"] = 6
df.loc[df["trial_id"] == 1, "stress_scale"] = 3

df.loc[df["trial_id"] == 2, "exertion_scale"] = 5.5
df.loc[df["trial_id"] == 2, "stress_scale"] = 6.5

# Remove trial 3 and 4 if they already exist, so we do not duplicate them
df = df[~df["trial_id"].isin([3, 4])]

# Add trial 3 and trial 4
new_rows = pd.DataFrame([
    {
        "trial_id": 3,
        "date": "2026-06-24",
        "condition": "calm",
        "resting_hr": 75,
        "post_exercise_hr": 143,
        "hr_60s": 88,
        "hrr": 55,
        "completion_time": "N/A",
        "side_notes": "8 hours of sleep; timer shut off at 50 seconds remaining, had to guess; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 3 mistakes were made while skipping",
        "exertion_scale": 5.5,
        "stress_scale": 3
    },
    {
        "trial_id": 4,
        "date": "2026-06-24",
        "condition": "stress",
        "resting_hr": 75,
        "post_exercise_hr": 153,
        "hr_60s": 91,
        "hrr": 62,
        "completion_time": "2:03.30",
        "side_notes": "8 hours of sleep; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 4 mistakes were made while skipping; made a mistake when doing serial sevens test - did not end at 4, ended on 6",
        "exertion_scale": 6.5,
        "stress_scale": 6.5
    }
])

df = pd.concat([df, new_rows], ignore_index=True)

# Recalculate HRR
df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

# Save the updated table
df.to_csv(data_path, index=False)

df

TypeError: Invalid value '5.5' for dtype 'Int64'

In [7]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path, keep_default_na=False)

# Make sure trial_id is treated as a number
df["trial_id"] = pd.to_numeric(df["trial_id"], errors="coerce").astype("Int64")

# Add the two new columns if they do not already exist
if "exertion_scale" not in df.columns:
    df["exertion_scale"] = pd.NA

if "stress_scale" not in df.columns:
    df["stress_scale"] = pd.NA

# These columns need to allow decimals, so use Float64, not Int64
df["exertion_scale"] = pd.to_numeric(df["exertion_scale"], errors="coerce").astype("Float64")
df["stress_scale"] = pd.to_numeric(df["stress_scale"], errors="coerce").astype("Float64")

# Add scale values for existing trials 1 and 2
df.loc[df["trial_id"] == 1, "exertion_scale"] = 6
df.loc[df["trial_id"] == 1, "stress_scale"] = 3

df.loc[df["trial_id"] == 2, "exertion_scale"] = 5.5
df.loc[df["trial_id"] == 2, "stress_scale"] = 6.5

# Remove trials 3 and 4 if they already exist, so we do not duplicate them
df = df[~df["trial_id"].isin([3, 4])]

# Add trials 3 and 4
new_rows = pd.DataFrame([
    {
        "trial_id": 3,
        "date": "2026-06-24",
        "condition": "calm",
        "resting_hr": 75,
        "post_exercise_hr": 143,
        "hr_60s": 88,
        "hrr": 55,
        "completion_time": "N/A",
        "side_notes": "8 hours of sleep; timer shut off at 50 seconds remaining, had to guess; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 3 mistakes were made while skipping",
        "exertion_scale": 5.5,
        "stress_scale": 3
    },
    {
        "trial_id": 4,
        "date": "2026-06-24",
        "condition": "stress",
        "resting_hr": 75,
        "post_exercise_hr": 153,
        "hr_60s": 91,
        "hrr": 62,
        "completion_time": "2:03.30",
        "side_notes": "8 hours of sleep; approximately 3 hours and 30 minutes after 30 minute HIIT workout; 4 mistakes were made while skipping; made a mistake when doing serial sevens test - did not end at 4, ended on 6",
        "exertion_scale": 6.5,
        "stress_scale": 6.5
    }
])

df = pd.concat([df, new_rows], ignore_index=True)

# Make sure heart rate columns are numbers
df["post_exercise_hr"] = pd.to_numeric(df["post_exercise_hr"], errors="coerce")
df["hr_60s"] = pd.to_numeric(df["hr_60s"], errors="coerce")

# Recalculate HRR
df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

# Save the updated table
df.to_csv(data_path, index=False)

df

,trial_id,date,condition,resting_hr,post_exercise_hr,hr_60s,hrr,completion_time,side_notes,exertion_scale,stress_scale
0,1,2026-06-21,calm,75,141,83,58,N/A,"Approx 2h after hitting with Richard, 8 hours ...",6.0,3.0
1,2,2026-06-21,stress,75,144,86,58,2:17.46,"Approx 2h after hitting with Richard, 8 hours ...",5.5,6.5
2,3,2026-06-24,calm,75,143,88,55,N/A,8 hours of sleep; timer shut off at 50 seconds...,5.5,3.0
3,4,2026-06-24,stress,75,153,91,62,2:03.30,8 hours of sleep; approximately 3 hours and 30...,6.5,6.5

In [8]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data_path = project_root / "data" / "research_data.csv"

df = pd.read_csv(data_path, keep_default_na=False)

# Make sure trial_id is numeric
df["trial_id"] = pd.to_numeric(df["trial_id"], errors="coerce").astype("Int64")

# Make sure the two scale columns exist
if "exertion_scale" not in df.columns:
    df["exertion_scale"] = pd.NA

if "stress_scale" not in df.columns:
    df["stress_scale"] = pd.NA

# These columns allow decimals like 5.5 or 6.5
df["exertion_scale"] = pd.to_numeric(df["exertion_scale"], errors="coerce").astype("Float64")
df["stress_scale"] = pd.to_numeric(df["stress_scale"], errors="coerce").astype("Float64")

# Remove trials 5 and 6 if they already exist, so we do not accidentally duplicate them
df = df[~df["trial_id"].isin([5, 6])]

new_rows = pd.DataFrame([
    {
        "trial_id": 5,
        "date": "2026-06-25",
        "condition": "calm",
        "resting_hr": 70,
        "post_exercise_hr": 135,      # TODO: replace this
        "hr_60s": 81,                # TODO: replace this
        "hrr": 54,
        "completion_time": "N/A",
        "side_notes": "About 8 hours sleep (maybe 8.5?); 2 mistakes were made while skipping; sore in glutes from yesterday's HIIT workout; no workout or physcial activity was done today",           # TODO: replace this
        "exertion_scale": 4.5,        # TODO: replace this
        "stress_scale": 2           # TODO: replace this
    },
    {
        "trial_id": 6,
        "date": "2026-06-25",
        "condition": "stress",
        "resting_hr": 70,
        "post_exercise_hr": 134,      # TODO: replace this
        "hr_60s": 76,                # TODO: replace this
        "hrr": 64,
        "completion_time": "1:30.76",      # TODO: replace this
        "side_notes": "About 8 hours sleep (maybe 8.5?); 5 mistakes were made while skipping; had mild cramp after making 3 mistakes at 1:30; watch took a couple of seconds after skipping to give heart rate; sore in glutes from yesterday's HIIT workout; no workout or physcial activity was done today",           # TODO: replace this
        "exertion_scale": 5,        # TODO: replace this
        "stress_scale": 5.5           # TODO: replace this
    }
])

df = pd.concat([df, new_rows], ignore_index=True)

# Make sure HR columns are numbers
df["post_exercise_hr"] = pd.to_numeric(df["post_exercise_hr"], errors="coerce")
df["hr_60s"] = pd.to_numeric(df["hr_60s"], errors="coerce")

# Calculate HRR automatically
df["hrr"] = df["post_exercise_hr"] - df["hr_60s"]

# Save the updated table
df.to_csv(data_path, index=False)

df

,trial_id,date,condition,resting_hr,post_exercise_hr,hr_60s,hrr,completion_time,side_notes,exertion_scale,stress_scale
0,1,2026-06-21,calm,75,141,83,58,N/A,"Approx 2h after hitting with Richard, 8 hours ...",6.0,3.0
1,2,2026-06-21,stress,75,144,86,58,2:17.46,"Approx 2h after hitting with Richard, 8 hours ...",5.5,6.5
2,3,2026-06-24,calm,75,143,88,55,N/A,8 hours of sleep; timer shut off at 50 seconds...,5.5,3.0
3,4,2026-06-24,stress,75,153,91,62,2:03.30,8 hours of sleep; approximately 3 hours and 30...,6.5,6.5
4,5,2026-06-25,calm,70,135,81,54,N/A,About 8 hours sleep (maybe 8.5?); 2 mistakes w...,4.5,2.0
5,6,2026-06-25,stress,70,134,76,58,1:30.76,About 8 hours sleep (maybe 8.5?); 5 mistakes w...,5.0,5.5